name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:${{ github.sha }} .

      - name: List Docker Images
        run: docker images

      - name: List files in /app directory
        run: |
          docker run --rm ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:${{ github.sha }} ls /app

      - name: Run tests
        run: |
          docker run --rm -w /app ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:${{ github.sha }} \
          python -m unittest discover -s tests -p "*.py"

  push-to-dockerhub:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Pull built image from previous job (if needed)
        run: echo "No need to pull if cached; image should exist."

      - name: Tag and Push Docker image to Docker Hub
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:${{ github.sha }} ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:${{ github.sha }}
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/titanic-project:latest
